packer {
  required_plugins {
    hcloud = {
      version = ">= 1.5.0"
      source  = "github.com/hetznercloud/hcloud"
    }
  }
}

variable "git-sha" {
  type    = string
  default = "${env("CI_COMMIT_SHA")}"
}

variable "snapshot_name" {
  type = string
  default = "packer-{{timestamp}}"
}

variable "hcloud_api_token" {
  type      = string
  default   = "${env("HCLOUD_TOKEN")}"
  sensitive = true
}

variable "hcloud_upgrade_server_type" {
  type = string
  default = "${env("HCLOUD_SERVER_TYPE")}"
  sensitive = true
}

variable "hcloud_server_type" {
  type = string
  default = "${env("HCLOUD_SERVER_TYPE_BEFORE_UPSCALE")}"
  sensitive = true
}

variable "hcloud_server_location" {
  type = string
  default = "${env("HCLOUD_SERVER_LOCATION")}"
  sensitive = true
}

variable "ci_job_id" {
  type = string
  default = "${env("CI_JOB_ID")}"
  sensitive = true
}

source "hcloud" "autogenerated_1" {
  image       = var.hcloud_image
  location    = var.hcloud_server_location
  server_name = "hcloud-app-builder-${var.app_name}-${var.ci_job_id}"
  server_type = var.hcloud_server_type
  upgrade_server_type = var.hcloud_upgrade_server_type
  snapshot_labels = {
    version   = var.app_version
    slug      = "oneclick-${var.app_name}-${var.app_version}-${var.hcloud_image}"
  }
  snapshot_name = var.snapshot_name
  ssh_username  = "root"
  token         = var.hcloud_api_token
}
