variable "git-sha" {
  type    = string
  default = "${env("GITHUB_SHA")}"
}

variable "snapshot_name" {
  type = string
  default = "packer-{{timestamp}}"
}

variable "hcloud_api_token" {
  type      = string
  default   = "${env("HCLOUD_API_TOKEN")}"
  sensitive = true
}

variable "hcloud_upgrade_server_type" {
  type = string
  default = "${env("HCLOUD_SERVER_TYPE")}"
  sensitive = true
}

variable "hcloud_server_type" {
  type = string
  default = "${env("HCLOUD_BASE_SERVER_TYPE")}"
  sensitive = true
}

variable "hcloud_server_location" {
  type = string
  default = "${env("HCLOUD_SERVER_LOCATION")}"
  sensitive = true
}

source "hcloud" "autogenerated_1" {
  image       = var.hcloud_image
  location    = var.hcloud_server_location
  server_name = "hcloud-app-builder-${var.app_name}-{{timestamp}}"
  server_type = var.hcloud_server_type
  snapshot_labels = {
    git-sha   = var.git-sha
    version   = var.app_version
    slug      = "oneclick-${var.app_name}-${var.app_version}-${var.hcloud_image}"
  }
  snapshot_name = var.snapshot_name
  ssh_username  = "root"
  token         = var.hcloud_api_token
}
