#!/bin/bash

# Generate passwords
mysql_root_pass=$(openssl rand -hex 24)
nextcloud_mysql_pass=$(openssl rand -hex 24)
debian_sys_maint_mysql_pass=$(openssl rand -hex 24)

# Don't enable Nextcloud until first login
cat >> /root/.bashrc <<EOM
chmod +x /opt/hcloud/nextcloud_setup.sh
/opt/hcloud/nextcloud_setup.sh
EOM

# Save the passwords
cat > /root/.hcloud_password <<EOM
mysql_root_pass="${mysql_root_pass}"
nextcloud_mysql_pass="${nextcloud_mysql_pass}"
EOM


mysqladmin -u root -h localhost create nextcloud
mysqladmin -u root -h localhost password ${mysql_root_pass}

chown -Rf www-data:www-data /var/www/nextcloud

mysql -uroot -p${mysql_root_pass} \
      -e "CREATE USER 'nextcloud'@'localhost' IDENTIFIED BY '${nextcloud_mysql_pass}'"

mysql -uroot -p${mysql_root_pass} \
      -e "GRANT ALL PRIVILEGES ON nextcloud.* TO nextcloud@localhost"

mysql -uroot -p${mysql_root_pass} \
      -e "ALTER USER 'debian-sys-maint'@'localhost' IDENTIFIED BY '${debian_sys_maint_mysql_pass}'"

MYSQL_ROOT_PASSWORD=${nextcloud_mysql_pass}

SECURE_MYSQL=$(expect -c "
set timeout 10
spawn mysql_secure_installation
expect \"Enter current password for root (enter for none):\"
send \"$MYSQL_ROOT_PASSWORD\r\"
expect \"Change the root password?\"
send \"n\r\"
expect \"Remove anonymous users?\"
send \"y\r\"
expect \"Disallow root login remotely?\"
send \"y\r\"
expect \"Remove test database and access to it?\"
send \"y\r\"
expect \"Reload privilege tables now?\"
send \"y\r\"
expect eof
")

cat > /etc/mysql/debian.cnf <<EOM
# Automatically generated for Debian scripts. DO NOT TOUCH!
[client]
host     = localhost
user     = debian-sys-maint
password = ${debian_sys_maint_mysql_pass}
socket   = /var/run/mysqld/mysqld.sock
[mysql_upgrade]
host     = localhost
user     = debian-sys-maint
password = ${debian_sys_maint_mysql_pass}
socket   = /var/run/mysqld/mysqld.sock
EOM
