variable "app_name" {
  type    = string
  default = "mealie"
}

variable "app_version" {
  type    = string
  default = "v1.0.0beta-5"
}

variable "hcloud_image" {
  type    = string
  default = "ubuntu-22.04"
}

build {
  sources = ["source.hcloud.autogenerated_1"]

  provisioner "shell" {
    inline = ["cloud-init status --wait"]
  }

  provisioner "file" {
    destination = "/opt/"
    source      = "apps/hetzner/mealie/files/opt/"
  }

  provisioner "file" {
    destination = "/var/"
    source      = "apps/hetzner/mealie/files/var/"
  }

  provisioner "shell" {
    environment_vars = ["DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8"]
    scripts          = ["apps/shared/scripts/apt-upgrade.sh", "apps/hetzner/mealie/scripts/install.sh", "apps/shared/scripts/cleanup.sh"]
  }
}
