variable "app_name" {
  type    = string
  default = "go"
}

variable "app_version" {
  type    = string
  default = "1.19.4"
}

variable "app_checksum" {
  type    = string
  default = "c9c08f783325c4cf840a94333159cc937f05f75d36a8b307951d5bd959cf2ab8"
}

variable "hcloud_image" {
  type    = string
  default = "ubuntu-22.04"
}

build {
  sources = ["source.hcloud.autogenerated_1"]

  provisioner "shell" {
    inline = ["cloud-init status --wait"]
  }

  provisioner "shell" {
    environment_vars = ["application_version=${var.app_version}", "application_checksum=${var.app_checksum}", "DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8"]
    scripts          = ["apps/shared/scripts/apt-upgrade.sh", "apps/hetzner/go/scripts/go.sh", "apps/shared/scripts/cleanup.sh"]
  }

}
