variable "app_name" {
  type    = string
  default = "go"
}

variable "app_version" {
  type    = string
  default = "1.20.1"
}

variable "app_checksum_amd64" {
  type    = string
  default = "000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02"
}

variable "app_checksum_arm64" {
  type    = string
  default = "5e5e2926733595e6f3c5b5ad1089afac11c1490351855e87849d0e7702b1ec2e"
}

variable "hcloud_image" {
  type    = string
  default = "ubuntu-22.04"
}

build {
  sources = ["source.hcloud.autogenerated_1"]

  provisioner "shell" {
    inline = ["cloud-init status --wait --long"]
    valid_exit_codes = [0, 2]
  }

  provisioner "shell" {
    environment_vars = ["application_version=${var.app_version}", "application_checksum_amd64=${var.app_checksum_amd64}", "application_checksum_arm64=${var.app_checksum_arm64}", "DEBIAN_FRONTEND=noninteractive", "LC_ALL=C", "LANG=en_US.UTF-8", "LC_CTYPE=en_US.UTF-8"]
    scripts          = ["apps/shared/scripts/apt-upgrade.sh", "apps/hetzner/go/scripts/go.sh", "apps/shared/scripts/cleanup.sh"]
  }

}
