---
name: hetzner/docker-ce

on:
  workflow_dispatch:
  push:
    paths:
      - "apps/hetzner/docker-ce/**"
      - ".github/workflows/packer-docker-ce.yml"
      - "apps/shared/**"

jobs:
  packer:
    runs-on: [self-hosted, Linux, X64]
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: apps/hetzner/docker-ce/

      # build artifact
      - name: Build Docker CE
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: apps/hetzner/docker-ce/
        env:
          HCLOUD_API_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.HCLOUD_API_TOKEN || secrets.HCLOUD_API_TOKEN_STAGING }}

  cleanup:
    runs-on: [self-hosted, Linux, X64]
    needs: packer
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/cleanup.sh docker-ce
        env:
          HCLOUD_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.HCLOUD_API_TOKEN || secrets.HCLOUD_API_TOKEN_STAGING }}
