---
name: hetzner/docker-ce

on:
  push:
    paths:
      - "apps/hetzner/docker-ce/**"
      - ".github/workflows/packer-docker-ce.yml"
      - ".github/actions/build-image/**"
      - "apps/shared/**"
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  packer:
    runs-on: [self-hosted, Linux, X64]
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/build-image
        with:
          app: docker-ce
          token: ${{ github.ref == 'refs/heads/main' && secrets.HCLOUD_API_TOKEN || secrets.HCLOUD_API_TOKEN_STAGING }}
          server_location: ${{ secrets.HCLOUD_SERVER_LOCATION }}
          server_type: ${{ secrets.HCLOUD_SERVER_TYPE }}
          base_server_type: ${{ secrets.HCLOUD_BASE_SERVER_TYPE }}
